apiVersion: v1
kind: Service
metadata:
  name: goserver-service
spec: 
  type: ClusterIP
  ports:
    - protocol: TCP
      name: http-svc
      port: 3000
  selector:
    app: server
---
apiVersion: v1
kind: Service
metadata:
  name: goserver-lb
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
  selector:
    app: server