apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: api
  namespace: api
spec:
  dnsNames:
    - api.lustepe.xyz
  secretName: api-tls
  issuerRef:
    name: go-api-cluster-issuer-key
    kind: ClusterIssuer