apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: go-api-cluster-issuer-key
  namespace: api
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lustepe@gmail.com
    privateKeySecretRef:
      name: go-api-cluster-issuer-key
    solvers:
    - http01:
        ingress:
          class: nginx
    - dns01:
        webhook:
          groupName: acme.blackhouse.dev
          solverName: godaddy
          config:
            authAPIKey: Tdy4mwPEoSfuSLszfhYm8r
            authAPISecretRef:
              name: godaddy-api-key
              key: eoX5FNxmdQut_3tq3mnyQzfHQeWbh4dszam
