apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: letsencrypt-api
  namespace: cert-manager
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: lustepe@gmail.com
    privateKeySecretRef:
      name: letsencrypt-api
    solvers:
    - http01:
        ingress:
          class: nginx