
version: '3'

services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "noah123!"
    ports:
      - "3306:3306"
    volumes:
      - /home/lucas/dev/docker/mysql:/var/lib/mysql