apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: noah
  namespace: noah-api
spec:
  interval: 5m
  chart:
    spec:
      chart: noah-api
      version: '>=0.1.0 <0.3.0'
      sourceRef:
        kind: HelmRepository
        name: noah
        namespace: noah-api
      interval: 1m
  values:
    containers:
      imageName: lustepe/simple-server-nodejs:v2
      envFrom:
        configMap:
          data:
            MY_NAME: Tatiane
      